name: Laravel

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push of Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/xenarisis/projet-saonelocal:latest

  newman-test:
    name: Newman Test
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Give perms *
        run: chmod -R 777 .
      
      - name: Starting API
        run: docker compose -f docker-compose.yml up -d
      
      - name: Install Newman & Wait-on
        run: npm install -g newman wait-on
      
      - name: Waiting API and BDD
        run: wait-on http-get://localhost:8000/api/health -t 120000
      
      - name: Run Postman Collection
        run: |
          for file in tests/api/*.postman_collection.json; do
            echo "Run collection : $file"
            newman run "$file"
          done

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [docker-build-and-push, newman-test]
    if: github.ref == 'refs/heads/main' 
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Cp to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml,docker/nginx/"
          target: "/home/${{ secrets.EC2_USERNAME }}/projet-saonelocal"

      - name: Deploying using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            cd /home/${{ secrets.EC2_USERNAME }}/projet-saonelocal
            
            sudo docker compose -f docker-compose.prod.yml pull
            sudo docker compose -f docker-compose.prod.yml up -d
            
            sudo docker image prune -af